### ISSUE TITLE
Add warning "Results are incomplete and may change"

### ISSUE THREAD

**Issue by sebastianotronto** [thewca/wca-live#109]
Hello software team,

For a competitor it can be very frustrating to find out they did not advance to the next round even though they had previously checked the live results and thought they qualified. This can happen for example when some results are entered late or when the number of advancing competitors is changed due to no-shows being removed (if the advancement criterion is set to a percentage of total competitors). Unfortunately the Disciplinary Committee is relatively often notified about this, either because a parent complains directly to us about the situation or because a delegate reports a heated discussion during a competition.

I think we could help mitigate this by adding a simple warning when the results are not completely entered. I could see this consist of two/three parts:

- On the result page for a round, right below the name of the event, a warning, possibly highlighted in yellow or red: "Results for this round are incomplete. Rankings and qualification limits may change."
- On the competitor's result page, a question mark next to rankings for incomplete rounds, showing the same message as above when clicked or tapped.
- Same as the previous point on the mobile version when clicking/tapping on a competitor's name from the round results page.

Another idea is to not highlight any ranking in green before the results are complete. This is compatible, but not dependent on, the warning message proposal I explained above.

I hope you can consider implementing something like this soon, but I understand that you are probably busy with more important stuff. If you can think of a different way to solve the same problem feel free to implement that instead :)

Thank you,
Sebastiano

**Comment by Goosly** [comment]
Indeed this confuses and frustrates competitors and parents very often.

To me, not highlight any ranking in green before the results are complete seems the way to go.

**Comment by jonatanklosko** [comment]
I think we should show the highlight, because it encodes relevant information when looking at live results.

For the percentage-based rules I think computing it based on the currently entered results can be slightly confusing, because that dynamically changes the number of advancing competitions. However, given the incidents you both mentioned I agree that it is a better approach as it prevents from false positives.

FTR I also feel that indicators like questions marks or stars are not clear enough, and showing an explicit message whenever the round is running is too much. So I would start with #111.

**Comment by jonatanklosko** [comment]
Closed in #111.
