### ISSUE TITLE
Change design of "PR" tag to be more easily distinguishable from NR/CR

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/wca-live#126]
Again referencing [this forum thread](https://forum.worldcubeassociation.org/t/changing-wca-live-to-pr-instead-of-pb/28111/11), the change from "PB" to "PR" has been implemented, but as multiple users note, it looks a bit confusing as the design is very similar to the NR/CR tag. 

@nsilvestri would you be interested in an update to #122 where you make a minor design change to the tag? My first thought would be to make it more opaque and thus less attention-grabbing than the NR/CR tags (I don't think a pure colour change would be enough, as I think NR/CR are already different colours?). I'm not a UI designer, though, so up to you :D

**Comment by nsilvestri** [comment]
Thanks for the feedback Duncan, I've been monitoring the response to this as well. I've thrown together a quick alternative, and I'd appreciate feedback on it. Note that these styles apply globally to the PR tag, not just on the round results table. 

Dark mode:

![image](https://user-images.githubusercontent.com/33607815/204075798-a0fc33b8-b3e0-4f3f-a829-59b21893f0eb.png)


Light mode:

![image](https://user-images.githubusercontent.com/33607815/204075810-ee4144ce-b2cc-4bb5-b64a-0b308d67bc33.png)

**Comment by jonatanklosko** [comment]
@nsilvestri I think there isn't enough contrast between the tag background and page background. I would try reversing the background and font colour, so on light mode it can be a dark grey background and white font.

**Comment by nsilvestri** [comment]
@jonatanklosko here's the inverse of the previous iteration:

![image](https://user-images.githubusercontent.com/33607815/204098436-3ce82e70-3daf-4a11-abee-a3aa0ae0775f.png)

![image](https://user-images.githubusercontent.com/33607815/204098455-82a7954b-2396-472a-b2a3-242798812b31.png)

In my own opinion, this is about equally as attention-grabbing as the original iteration, especially on light mode. Maybe the solution to this problem is keeping the blue PR tags, but hiding them behind a user-controlled switch that toggles showing/hiding PRs? The switch would pass a `hidePr` prop to the `RecordTagBadge`s on the `RoundResultsTable`.

**Comment by jonatanklosko** [comment]
Yeah, I agree that feel to much, but if there are are a lot of PRs I think any colour will have this issue. So another alternative I can think of is removing the background entirely, with a little less padding; this way it wouldn't stand out, but the information would be there.

(Theoretically we could have a user configuration flag, but I'd rather figure out a design that is not concerning and then let people get used to it)

**Comment by nsilvestri** [comment]
Here's a version with `0.1em` left and right padding and no background color. 

![image](https://user-images.githubusercontent.com/33607815/204114232-21397cd4-4475-42ca-af2c-e43b9f12a13d.png)
![image](https://user-images.githubusercontent.com/33607815/204114246-e2c991e5-2772-485c-86b6-09634180e88f.png)

It's not terrible, but in my opinion it now feels like the PR badge has some styling error because it's not consistent with the other badges. I'll admit my personal favorite so far is the first draft, with light gray on light theme/dark gray on dark theme. Maybe these designs could be put to a poll to get some more community feedback?

**Comment by dunkOnIT** [comment]
My personal bias is also towards the first iteration - I think it is clearly different from NR/CR and doesn't grab attention unnecesarily, but is still easily visible and distinguishable - especially to someone looking for 

I think waiting for a bit more community feedback in the forum thread should get us there - but we can try and solicit more if needed.

**Comment by jonatanklosko** [comment]
Alright, I'm ok with the first one then :)

**Comment by nsilvestri** [comment]
@jonatanklosko what if PR badge had this lower contrast style only on the round results table, while it stayed blue in all other contexts? I think there's value in maintaining the higher visibility color in the dialog boxes and competitor results table, and would allow the best of both worlds.

As a preliminary complexity analysis, I'd probably implement it with a `RecordTagProps` that gets passed as a prop to the `RecordTagBadge` in `RoundResultsTable`, which then gets spread in the `RecordTag` props, allowing a sort of one-off override of the styles specified in the `RecordTag`.

**Comment by jonatanklosko** [comment]
@nsilvestri I'm not sure if having two distinct variants for PRs is going to be confusing, but we can start with that and see.

As for the implementation I'd rather add `litePr` flag, rather than style overrides, just to encapsulate that variant more :)

**Comment by jonatanklosko** [comment]
Closed in #127.
