### ISSUE TITLE
Event not finished when DNF with longer time than acumulative limit

### ISSUE THREAD

**Issue by Citaborg** [thewca/wca-live#131]
I had a competitor that did DNF in the first attempt on blind where we had 10 minute accumulative time limit. . The DNF was done on the time: 10:01:59 so competitor should not be allowed to try again. 
When looking at podium in WCA-Live the event is not considered done in WCA-live. (If I fill all with DNF or all with DNS it is marked as complete. See last row in result table below))
![image](https://user-images.githubusercontent.com/3041020/209859641-1aae7c39-8ba2-4b47-ae6a-f4188a4fa84c.png)

**Comment by jonatanklosko** [comment]
Interesting case, I would actually expect those solves to be either DNF or DNS (i.e. if the cube is scrambled DNF with 0:00, otherwise DNS). I thought we use skipped solves only for cutoffs, where the competitors is expected to do less solves. @Jambrose777 @SAuroux is there a clear guideline for this case?

**Comment by SAuroux** [comment]
See https://github.com/thewca/wca-regulations/pull/1049 and https://forum.worldcubeassociation.org/t/readdition-of-guideline-a1a2/18218

Further comment: a cumulative time limit is no cutoff and every competitor must always have N results for a round with N attempts if there is no cutoff.

**Comment by jonatanklosko** [comment]
@SAuroux perfect, thank you for the clarification!

@Citaborg so those should be DNS :)
