### ISSUE TITLE
Double alert

### ISSUE THREAD

**Issue by pawelduraj** [thewca/wca-live#137]
After entering the results for the first round and opening the second round, when we go to the first round again, the alert appears twice.
![messages](https://user-images.githubusercontent.com/49090420/213659742-439eadf7-7e1d-4e19-8580-dc3048261874.png)

**Comment by jonatanklosko** [comment]
It would only happen in development, because `<React.StrictMode>` mounts every component twice to help detect bugs where side effects are not cleaned up on component removal. In this case it is kinda relevant, because if someone goes to the round, then quickly navigates back, the snackbar would disappear after 5 seconds rather than immediately, so overall good catch :)

Closed in 83c1a4a64e404e5475c75110fa82a8e7e92d08f1.
