### ISSUE TITLE
Adding warning when submitting regional record

### ISSUE THREAD

**Issue by MariaBeau** [thewca/wca-live#142]
Similar to cubecomps, when a national/continental/world record time is inputted before the time can be submitted a warning should be given. This would be similar to the inconsistency warning that already exists. 

We've had a number of occasions where a non-cuber did data entry and accidentally inputted a false world record, which was quite embarrassing for them and subsequently caused them to refrain from doing data entry. This issue can also occur quite easily when results are inputted for the wrong event.

**Comment by OJCubing** [comment]
I would limit this to just Continental/World Records. National Records can be very frequent at some competitions so it would get irritating to dismiss them every time, but CR/WR would frequently catch out mistakes. I very much support bringing this feature back though!

**Comment by jonatanklosko** [comment]
Closed in #157.

For now it's just world records. We could do continental records too, but it's a bit more involved and I think the general idea is to detect suspiciously low times (in case someone enters results in a wrong event, etc). Rather than continental records it may be more useful to check for times within some percentage from WR, but we can revisit if we notice a specific category of false positives.
