### ISSUE TITLE
Manual refreshing was required to get result updates during 3x3 Finals

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/wca-live#177]
Several users have reported this, and I also experienced it myself - results stopped updated automatically for clients, and a refresh (F5) was required to see more results. It would be good to understand the cause of this behaviour if possible.

**Comment by dunkOnIT** [comment]
It is possible this was due to many people having WCA Live on their second monitors/out of focus. 

1. I assume there is no way to keep updating results even when out of focus? 
2. If no to (1), perhaps we can have an event that triggers a sync when WCA Live comes into focus?

**Comment by jonatanklosko** [comment]
> I assume there is no way to keep updating results even when out of focus?

The results definitely do update out of focus, so that's not it.

For me the updates worked until the last entered attempt. I don't have a sure guess as to why that was. Technically this could happen if a node went down and basically a realtime event was missed in the cluster, but iirc infrastructure was looking stable during finals. This could also happen if the websocket was disconnected for whatever reason, though it does reconnect, so it's a small window to miss the event.

I'm not sure if there's anything particularly actionable. One thing worth checking would be spawning a huge number of instances (20/30) and verifying that they are indeed properly connected to each other.

**Comment by maxidragon** [comment]
This also happened to me during the Euros 3x3 finals. I had to refresh after almost every solve

**Comment by jonatanklosko** [comment]
I noticed this during Asian Championship finals. There were ~10 instances running, so I connected to one of them and run `Node.list()` a few times, which essentially says which other instances the current instance is connected to. I noticed the list was constantly changing, nodes were being connected and disconnected all the time.

The issue is that AWS DNS returns only up to 8 IPs for multi-value queries, so if there are more instances registered in that DNS, every query would get a random 8 IP subset.

A second part of this issue is how the clustering library works. It queries the DNS to see which instances are available and connects to them. However, it explicitly **disconnects** form already connected instances, if they are not returned in the DNS query, which explains the constant disconnects.

I changed to the library used for clustering (to a newer, smaller one, that specifically only implements DNS discovery), and it does not do explicit disconnects, so we don't run into this issue.

I deployed the change, bumped to 10 instances and verified that the instances are reliably connected, so I believe we are good. The relevant commit f6af5689d4dd3b1640cdfeae218cc9d4d1b0d09f.

This was definitely the reason for the original issue, because it seemed to appear only for high-traffic comps (at which points we would have 8+ instances), and disconnected cluster means a client connected to instance A, wouldn't get notified about result entered via instance B.
