### ISSUE TITLE
Batch Mode to order by batch timestamp first and then by scorecard timestamp

### ISSUE THREAD

**Issue by OJCubing** [thewca/wca-live#188]
Having 2 people do data entry for the same round simultaneously can be a pain, but batch mode *could* be enhanced to make it much easier.

Say we have Batches A and B and scorecards 1-6. Person A enters scorecard 1, then Person B enters scorecard 2, then alternating so A does the odds and B does the evens. Batch A is submitted after entering scorecard 5 and Batch B after scorecard 6.

Currently: When both batches are submitted, the scorecards are ordered by submission timestamp, i.e. 1-6. But Person A has 1,3,5 in their pile and Person B has 2,4,6 in their pile.

Suggestion: The scorecards are *first* ordered by the submission timestamp of the *batch*, and then scorecards within that batch are ordered by the submission timestamp of the scorecard. This would now order the scorecards as 1,3,5,2,4,6. Now Person B can stack their scorecards directly on top of Batch A and the order will be preserved. Alternatively, if Person B now wanted to double check their scorecards whilst Person A started entering Batch C, all of the scorecards within their batch would be kept together.

This will make double checking much much better for batch entry, which means it will be a huge improvement to being able to enter data simultaneously across multiple devices. Imo this could be a crucial change for large competitions and major championships.

**Comment by jonatanklosko** [comment]
We don't store batch submission time, but that wouldn't help entirely since people may be submitting batches more often than once per whole pile, so it's the same issue just less granular.

What we could do however, is to change the order in double-check such that we first group by the scoretaker, then by timestamp.

**Comment by OJCubing** [comment]
That sounds like a much cleaner solution! That wouldn't necessitate needing to switch to batch mode to make use of this feature either.

**Comment by OJCubing** [comment]
Just a thought - does scoretaker refer to the account that's logged in? In the UK we will have a couple of laptops both logged into the UKCA account, so if there could be a way to distinguish between them that would be super useful to us!

**Comment by jonatanklosko** [comment]
Hm yeah that wouldn't work. We could keep track of user sessions, but I think this is too brittle. Generally it's best if each scoretaker has an account. They can sign in using one-time-code, so that they don't have to type any passwords on these laptops, and if they are signed-in on their phones this should be pretty straightforward.

**Comment by OJCubing** [comment]
Closing this now as it isn't quite relevant, and made a new issue #196 to capture it more accurately.

**Comment by jonatanklosko** [comment]
Closing, as this is tracked in #133.
