### ISSUE TITLE
"Pending" indicator for rounds still active

### ISSUE THREAD

**Issue by Tobus2** [thewca/wca-live#194]
The current system uses a green "advancing" style for the first xx results even if there are some more results to come in. This can lead to people thinking they've made the cut off when they haven't.

Would it be better to have a "pending" indicator (orange, or faded/striped green, or something?) if there's a possibility that the result won't make the cutoff, and only use "advancing" when advancement is guaranteed? Eg 60 people go through and there's only 100 out of 120 results in so far: at present the current top 60 are all shown as "advancing", my suggestion is that the top 40 would be "advancing", but positions #41-60 would be "pending" until more results come in.

I've had a quick look at the code and it doesn't look like it would be too hard to do - I could probably do it myself if it's agreed that it's a good idea.

**Comment by jonatanklosko** [comment]
We had some discussions in the past. We changed the percentage-based advancement to be computed based on results entered so far (https://github.com/thewca/wca-live/issues/109#issuecomment-1258830632), because there can be false positives if there are no-show competitors.

However, when we know the number of advancing competitors, I think it's better to show them. Especially for second rounds, having the "green space" where competitors "jump into" over other competitors makes for a better experience imo.

We may add some disclaimer that the advancement is not finalized, which we track in #128.
