### ISSUE TITLE
Add SOR/Kinch ranks 

### ISSUE THREAD

**Issue by Samuel-Baird** [thewca/wca-live#21]
It could be pretty cool to see a page where you could view competitors ranked by SOR or Kinch using the competition results (ex. For kinch WR is replaced by best result at the comp, PR is replaced by best result from the competitor) 

There is currently already [this website](https://comp-kinch.sylvermyst.com/) that does this with kinch ranks, but it would be nice to have something that is on WCA live as well, especially for competitions where prizes may be given to the best all rounders.

**Comment by jonatanklosko** [comment]
Currently I would consider this out of the scope of WCA Live. We may revisit additional rankings in the future.

I imagine that one side effect of integrating SOR/Kinch directly into WCA Live (making them more prominent), could be that people sign up for more events just so that they can boost their score a bit (without caring much about those additional events). One could make an argument that this is a good thing, but that could also artificially slow down competitions, so I am not convinced we should promote that.
