### ISSUE TITLE
Former WRs are not converted into CRs or NRs

### ISSUE THREAD

**Issue by OtaMota** [thewca/wca-live#210]
Recently, Dilshawn got a 3.35 WR average. However, Niklas got a 3.31 the day after. Dilshawn's 3.35 should now be converted into NAR, but it is not to be found.
![Screenshot 2024-02-18 at 12 24 55](https://github.com/thewca/wca-live/assets/130600666/00d18ea5-f258-4cc4-9d7f-4930ed85e6f1)

It instead uses the 4.21 NR average he got the previous round.
![Screenshot 2024-02-18 at 12 26 34](https://github.com/thewca/wca-live/assets/130600666/a763a681-6acc-42f5-b93b-58cd37204371)

The problem is that the 4.21 is no longer NR, the Former WR 3.35 is. Hopefully this can soon be fixed.

**Comment by jonatanklosko** [comment]
This is by design. The record tags represent the status from where the result happened, so if it is broken soon after, it should remain as WR. In the record list specifically, we want to avoid duplicates, so if there are multiple records (in this case WRs) of the same kind, we only show the better one.

It is a bit confusing in this case, because there is also the NR that we don't filter out, but the alternative of showing both WRs would probably be even more confusing (even more so for CRs and NRs which can be broken quite often).

Note that the record tags in WCA Live are not "binding", they are just indicators. For example if there two WRs at different competitions at the same day, only one of them will eventually be considered as WR in the official rankings, but in WCA Live we show both as WRs, because we limit record computation to each competition itself.
