### ISSUE TITLE
WR badge applied to result that isn't WR but faster than the WR listed on wca main site

### ISSUE THREAD

**Issue by kyh148** [thewca/wca-live#212]
Last weekend Niklas Aasen Eliasson got a 3.31 WR avg for clock at Lierskogen Vinterkubing 2024. Today he got a 3.34 avg at Flatåsen Open 2024, which is listed as WR and has the WR badge on the [comp's WCA Live page](https://live.worldcubeassociation.org/competitions/4433). The 3.31 isn't on the WCA main site yet, which leads me to suspect that new WCA Live results are only compared to records on the main site and not to records on WCA Live, causing this minor issue.

**Comment by jonatanklosko** [comment]
@SuperPro148 yeah this is expected. The reason is indeed that it is not in the official ranks yet, and on WCA Live record tag computation is limited to the given competition. So Round 2 would consider results form Round 1 when computing results, but it does not consider other competitions.

The reason for this is that considering all competitions would be expensive and complex. For example if someone breaks WR on one competition, we would need to recompute record tags on all relevant competitions (and each such computation requires looking at the previous rounds, etc). If the WR was accidental and it gets changed, we need to recompute again. This may seem manageable with WRs, but if we were to do that, it should also apply to CRs and NRs, which are more common, and have the additional dependency on competitors country. So we would end up recomputing a bunch of records very often.

The tags on WCA Live are not "binding" in any way, they are just indicators that are correct most of the time, but in rare cases like this they may indeed be inaccurate.

**Comment by kyh148** [comment]
Fair enough, that makes sense!
