### ISSUE TITLE
Podiums page is sorted alphabetically

### ISSUE THREAD

**Issue by IldenH** [thewca/wca-live#227]
During an awards ceremony we generally announce events in the same order as appears elsewhere on WCA ([live side panel](https://live.worldcubeassociation.org/competitions/5321), [rankings and records](https://www.worldcubeassociation.org/results/records), etc) but reversed such that 3x3 gets announced last. 

Currently if you're just reading from a phone going backwards on the list you can easily go in a strange order or even mention a non-main event like 2x2 last.

[Square-1 is first instead of multi-blind and 2x2 appears as the main event](https://live.worldcubeassociation.org/competitions/5321/podiums)

The optimal solution would not only put the events in the standard order, but also move the main event of the competition to the top.

**Comment by jonatanklosko** [comment]
There was actually no explicit ordering, fixed in 526ff36f1b8db2b371c326063b7557c596d39d4f.

Currently WCA Live doesn't know which is the main event, we could make the WCA API expose it, but that's a separate discussion. I think a consistent order everywhere makes sense. FWIW the WCA website currently also lists podiums in the usual order, regardless the main event ([example](https://www.worldcubeassociation.org/competitions/CFLGoesSideways2019)).
