### ISSUE TITLE
Sign in to new competitor issue

### ISSUE THREAD

**Issue by maconard** [thewca/wca-live#23]
Currently, it saved my oauth so when I sign out and click admin sign in, it auto logs into me. This kind of defeats the purpose of granting privileges to WCA accounts for score taking when it's not easy to sign into a new competitor, so everyone is doing score taking on my account. It can be done in browser settings by clearing saved info, but that doesn't seem optimal.

May I suggest a "sign in to new competitor" page, in the admin settings tab, possibly?

Open to other ideas/discussion on this. (And I know of the competition generic password login, but I like the idea of score taking being trackable by logged in WCA accounts.)

Cheers!

**Comment by jonatanklosko** [comment]
I see it as follows:
1. You sign in with your account.
2. You sign out of WCA Live.
3. You click sign in again.

The thing is that if you don't sign out of the WCA website before 3. then the WCA website immediately returns to WCA Live authenticating you and this is definitely the expected behavior! If you want to use the same machine to sign in as someone else, then you should make sure to sign out of the WCA website first.

Please correct me if I missed your point!

**Comment by maconard** [comment]
That sounds like the correct way to proceed, then! I will make sure to log out of the actual WCA site before doing this. Thanks Jonotan.

That said, do you think a change accounts idea in WCA live would be possible and/or warranted, to aid in the account changing process?

**Comment by jonatanklosko** [comment]
There's not much WCA Live could do in this case, it's how OAuth works in general (e.g. signing in with Google), you need to switch account within provider (here WCA website) to authenticate with the new account.
On a top level, if you have one computer both for a scoretaker and you, then one way would be having the scoretaker signed in in, and open incognito whenever the delegate/organizer needs to sign in for a moment.
