### ISSUE TITLE
Cursor doesn't jump to next result after a DNF result

### ISSUE THREAD

**Issue by sarahstrong314** [thewca/wca-live#30]

**Comment by jonatanklosko** [comment]
This is the expected behavior, as I believe it's more consistent for enter/tab/arrow to be a kind of approval of whatever you type and it makes the flow more consistent. Pretty sure it's just the matter of getting used to behavior different to Cubecomps. If after some time people will keep complaining, we can get back to the initial behavior.

**Comment by sarahstrong314** [comment]
What about a setting to turn this feature on/off? That way, the people who strongly prefer the way it was on cubecomps can enable this feature.

**Comment by jonatanklosko** [comment]
I think it's not a good candidate for a setting and enforcing a consistent behavior is preferable.

**Comment by jfly** [comment]
I agree. I personally found cubecomps's behavior very inconsistent and infuriating ;)
