### ISSUE TITLE
Export results JSON in UTF8 instead of CP932 encoding.

### ISSUE THREAD

**Issue by Jambrose777** [thewca/wca-live#34]
See "Questions about sending Kyoto Open results" email thread.

I believe this is the correct resolution to this issue. (if the solution needs to be changed, or this is an issue with the scramble matcher instead, please update the issue).

**Comment by jonatanklosko** [comment]
There is no export on WCA Live, the results are saved back to the WCA website using the API and Scrambles Matcher loads them the same way.

Also the problem was not with parsing the results, but scrambles.json generated by TNoodle. Not sure why the file ended up in non-utf8 encoding, @campos20, @suushiemaniac any ideas?

As this is not related to WCA Live, I'm gonna close this one.

**Comment by gregorbg** [comment]
Mh, I'm surprised by this finding as well. I will try to verify if this is a general TNoodle problem or just a one-time hiccup.

**Comment by gregorbg** [comment]
I was not able to reproduce this issue locally, but I think I still know why it happens.

The issue was originally reported by a Japanese Delegate for a Japanese competition. The [CP932 encoding](https://de.wikipedia.org/wiki/Codepage_932) is a Windows encoding that extends on Japanese Kanji characters.

I suspect that the Java runtime of the Japanese Delegates default to this CP932 encoding, so TNoodle will need a fix to override that default setting and encode in UTF-8 regardless of system standards.

**Comment by gregorbg** [comment]
FYI I have created a corresponding issue in TNoodle: https://github.com/thewca/tnoodle/issues/431

The translations for Fewest Moves should be fixed before proceeding with that issue, however.
