### ISSUE TITLE
Calculating ao5 after 4 results introduced

### ISSUE THREAD

**Issue by cdraugr** [thewca/wca-live#42]
![Ao5](https://user-images.githubusercontent.com/46168076/69501898-71246b80-0f1a-11ea-8958-5ea82dba5041.png)

Is it possible to calculate ao5 in cases like this?
It's more comfortable to check results during live finals like 5th solves is DNF / DNS.

**Comment by jonatanklosko** [comment]
I wasn't sure what's best here, on one side I see it'd be quite convenient, but technically a person with pending solves doesn't have an average, so showing it could cause some confusion.

**Comment by AlexKatyukov** [comment]
This is an ideas for that:

1. Not to show places for people who did not complete a whole average
2. Not to bold not complete average
3. Show both best possible average and worst

**Comment by danieljames-dj** [comment]
Should we really allow to submit an attempt with empty results unless the solves didn't meet the cutoff? Can we just disable the submit button in case any of the attempts are not entered? Otherwise, there are chances that the delegate submits results forgetting to enter the last solve(s) as DNS.

**Comment by jonatanklosko** [comment]
Submitting empty attempts is actually very intentional, it's the proper value when submitting partial results, e.g. filling remaining FMC attempts with DNS is not really accurate and introduces unnecessary noise to the results list (same for MBLD), the same goes for head-to-head finals if the results are entered in real-time.

Thinking about the issue again, I don't quite like the idea of showing the average before the results is actually valid. One idea that sounds better to me would be showing some information when hovering over a person (e.g. best/worst possible average, current mean of times), but that's also just an idea.

**Comment by danieljames-dj** [comment]
Oh ya. You have a valid point @jonatanklosko . In that case, I agree with you regarding not to show average.

**Comment by AlexKatyukov** [comment]
On hover info is a beautiful idea IMO. Maybe best and worst possible average, personal bests, result in previous round?

**Comment by jonatanklosko** [comment]
#179 added predicted BPA and WPA.
