### ISSUE TITLE
Be able to specify which rankings to show on Projector View

### ISSUE THREAD

**Issue by saranshgrover** [thewca/wca-live#43]
Currently the projector always shows all competitors with entered results - however one might like to only show up to a certain ranking - for example only show those who qualified for the next round etc.

**Comment by jonatanklosko** [comment]
Hmm, I think it's more friendly/fair to acknowledge all results when projecting results at a competition.

**Comment by Mollerz** [comment]
I tend to agree with @jonatanklosko here, not only this but it does rotate through all the results at a reasonable pace so it should get through. It also confirms for those who didn't quite make it that, in fact, they didn't quite make it, instead of "missing" results. It would be quite bad if someone missed out due to a typo or similar, but if they'd have been able to see it could have been spotted early enough.

**Comment by jonatanklosko** [comment]
Sounds like a sufficient argument to me! Closing for now, if someone feels strongly about this, feel free to discuss.

**Comment by AlexKatyukov** [comment]
Maybe just write something like `(+3 competitors without results)`?

**Comment by Mollerz** [comment]
> Maybe just write something like `(+3 competitors without results)`?

This still doesn't cover the issue that there may be a typo or mistake in results taking.

**Comment by saranshgrover** [comment]
This isn't necessary to be used when results are being entered. It's more for when results are done being entered.

For example: I would like names for all competitors who qualify for round 2 to show up on the projector along with the qualification time right before/while it's going on. It provides audience better experience knowing who's competing and competitors can confirm that they did/or did not qualify

I guess it's okay to show everything - but in my opinion, showing results for those who didn't qualify during a round makes no sense.
