### ISSUE TITLE
Feature Request: Eco Mode for Poor Internet Connectivity

### ISSUE THREAD

**Issue by Rubiks-boy** [thewca/wca-live#47]
Hi all,

Recently, I was delegating a competition where we had to rely on a phone hotspot to use WCA live. Due to poor cellular reception, it would take upwards of several seconds from pressing submit on card N to being able to type results for card N+1. 

Therefore, I am wondering if there could be a mode specifically for circumstances like this. I am not sure how this would be implemented (maybe batch cards together in one request? maybe some kind of "outbox" where you can type cards while previous cards are still being sent sequentially?) Ideally, it would also automatically recognize when to switch to this mode.

Thanks,
Adam

**Comment by EdHollingdale** [comment]
An Eco mode would be a huge feature - some sort of way that bundled scorecard entries into batches of 5 or 10 for upload. The problem with slow internet can become quite a problem at large competitions as the time it takes after entering a scorecard gets worse the more entries there are in the round. 

In Australia we typically use phone hotspots, and at larger comps this can lead to quite slow internet (since there are 400 people in the same area all using their phones). It isn't so bad when entering the first or second scorecard of a round (say a 1-2 second lag) but if you need to load 200+ results we were seeing loading times of 10 seconds on entering scorecard 200 for example.
