### ISSUE TITLE
Remove competitions from WCA Live after 1 month

### ISSUE THREAD

**Issue by Jambrose777** [thewca/wca-live#82]
Currently WCA live shows a list for all upcoming competitions and competitions in the past month. If you manually edit the URL to adjust the id, you can access competitions further in the past.

There is a couple of issues that this presents:
- When anonymizing someone's data, we currently have in our process to sync past competitions within the past month so that the data is not publicly accessible via WCA Live. But if someone scans/gathers data from WCA live's past competitions, the removed data can be recovered.
 - WRT cannot anonymize data for past competitions without knowing which specific id links to the competition's ID.
- Results for competitions posted on WCA are already stale and often times can come with changes on WCA that are not present on WCA Live.

**Comment by jonatanklosko** [comment]
> WRT cannot anonymize data for past competitions without knowing which specific id links to the competition's ID.

All competitions can be found using the search:

![image](https://user-images.githubusercontent.com/17034772/137772283-4f6d38fc-8fbb-47c7-9d9f-b58f124f6867.png)

We don't show older competitions on the homepage, since there would be a lot and old ones are not particularly relevant, but I think it's a nice option to get back to an old competition.

**Comment by danieljames-dj** [comment]
> But if someone scans/gathers data from WCA live's past competitions, the removed data can be recovered.

Hi Jacob, I didn't understand this part, how is it possible?

**Comment by SAuroux** [comment]
I think what Jacob means is that WCA live will still contain the competitor names after they are gone on the WCA website, when we do not know the WCA live ID to sync that specific competition. 

But it seems that with the comment by @jonatanklosko this is now a non-issue @Jambrose777 ? Well, no a "non-issue" per se, because we would still need to manually search for all the competitor's past competitions on WCA live and synchronize...

@jonatanklosko I wonder if there isn't a more efficient way to achieve this. Is there a way to get the WCA live ID for a given competitionId and initiate the synchronization for it via API? If so, @Jambrose777 could include this in his open PR https://github.com/thewca/worldcubeassociation.org/pull/6086.

**Comment by Jambrose777** [comment]
We discussed a different solution privately.
For Each competition we would somehow ping `https://live.worldcubeassociation.org/link/competitions/{wcacompetitionId}`. That will either return an error if the competition does not have a WCA Live Page: `{"errors":{"detail":"Not Found"}}` or redirect to `https://live.worldcubeassociation.org/competitions/{wcalivecompetitionId}`. So if it we do get the new url back then we can list those competitions on the Anon Process and link to the WCA Live page.
