### ISSUE TITLE
Round advancement condition by percentage using number of competitors registered rather than number present

### ISSUE THREAD

**Issue by louismeunier** [thewca/wca-live#98]
This issue is currently happening with [3x3 round 1](https://live.worldcubeassociation.org/competitions/981/rounds/14643) of Empire State Spring 2022. The round 2 advancement condition is set to top 50% of competitors, but WCA live is showing top 50% based on the number of registered competitors for the event (43/87) rather than the number of actual competitors (39/78).

Any help with this would be appreciated. 

EDIT: After opening round 2 in WCA live, the advancement condition fixed itself. However, it still remains misleading prior to opening the next round, particularly for competitors looking at the results on the website.

**Comment by jonatanklosko** [comment]
This behaviour is expected, the percent is calculated with respect to all results in the round. For competitors that miss the round you can remove their results from the round altogether, as the round goes. This happens automatically when opening the next run, hence the advancement updates.

The alternative would be to calculate the percent of currently entered results, but I think this would be way more confusing, as it would constantly change with new results being entered.

If I missed the point, please let me know :)

**Comment by viktorzenk** [comment]
Hi,

I agree with Jonatan that it would be confusing if it updated based on entered results, but it (in my opinion) really needs to update when competitors are quitted from the round, instead of waiting until the next round is opened.

An example of this being an issue:
At Warm Up Stockholm 2022 this weekend we had 170 people registered for 2x2 with 75% advancing from the first round, meaning top 127 people if everyone were to show up.
165 people ended up competing, and once all results had been entered and the 5 no-shows had been quitted from the round, WCA Live still showed top 127 competitors in green, even though only 123 people (75% of 165) were now allowed to go through.

A person placed 124-127 sent me a long email after the competition, explaining that he canceled his other plans for the day and prepared, practiced, and got himself psyched up for round 2, only to find out hours later when round 2 started that he had no longer advanced. He had even asked the score takers who assured him that he had advanced, since all results were entered and he still had a green marking (they were not aware of this issue).

I completely understand the frustration caused by this, and would much prefer if the number of advancing people updated immediately once somebody is quitted from a round. This would mean that you can always check if there is anyone without entered results, and if not, you can trust the green markers.

Is this something that could be implemented?
Also please let me know if I have missed any reason for why this wouldn't be a good idea.

Thanks!

**Comment by jonatanklosko** [comment]
@viktorzenk thanks for the report, this was indeed a bug! The advancement indicator would update when opening the next round, but not when removing competitors manually. I fixed this in 23ca1a6c3c2eba6d9da40839bed09c2bdbd215ec, I'm sorry for the confusion it caused.

@louismeunier now I wonder if what you described was exactly this case, that is, if you quitted the competitors manually and then noticed the advancement indicators were wrong. If that's the case then it's fixed, otherwise I don't think we should change the behaviour as per my previous comment :)

**Comment by viktorzenk** [comment]
Thank you so much for all the work you do!
